"""Card c8bb3279 / scenario ts_7bb8d426 — tagged-release marketplace.

The hybrid source policy (per CONTRIBUTING.md): on `main` the
marketplace.json plugin entry uses a relative ``./plugins/okto-pulse``
source; on a tagged release a release artifact is generated by
``tools/release/build_tagged_marketplace.py`` that rewrites the source
into a github-pinned dict. This test exercises the rewriter and
asserts the on-disk marketplace.json on `main` is untouched.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest


@pytest.mark.scenario("ts_7bb8d426")
@pytest.mark.card("c8bb3279-f003-48ae-b78e-9f6f70c2e562")
@pytest.mark.sprint("e18856b2-4d19-4f7b-91a0-2a9a9559d5f5")
@pytest.mark.spec("75fe081f-2e7f-4d38-ba73-57d47815c369")
def test_tagged_release_produces_github_pinned_marketplace_entry(
    tmp_path: Path,
    repo_root: Path,
    marketplace_json_path: Path,
) -> None:
    """Scenario ts_7bb8d426 — tagged release pins source to a git tag.

    GIVEN: marketplace.json on main has source=./plugins/okto-pulse
    WHEN:  build_tagged_marketplace.py runs with --tag v0.1.14
    THEN:  output marketplace.json has source={source:github, repo:...,
        ref:v0.1.14, path:plugins/okto-pulse}; main file unchanged
    """
    builder = repo_root / "tools" / "release" / "build_tagged_marketplace.py"
    assert builder.exists(), f"R1.2 deliverable missing: {builder}"
    output = tmp_path / "marketplace-v0.1.14.json"

    # main file pre-state: source is the relative string
    main = json.loads(marketplace_json_path.read_text(encoding="utf-8"))
    assert main["plugins"][0]["source"] == "./plugins/okto-pulse"

    result = subprocess.run(
        [
            sys.executable,
            str(builder),
            "--tag",
            "v0.1.14",
            "--output",
            str(output),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"build_tagged_marketplace failed:\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )

    tagged = json.loads(output.read_text(encoding="utf-8"))
    src = tagged["plugins"][0]["source"]
    assert isinstance(src, dict), (
        f"Expected source to be rewritten to a dict; got {src!r}"
    )
    assert src == {
        "source": "github",
        "repo": "oktolabsai/claude-plugins",
        "ref": "v0.1.14",
        "path": "plugins/okto-pulse",
    }, f"Unexpected pinned source: {src!r}"

    # main file unchanged
    assert (
        json.loads(marketplace_json_path.read_text(encoding="utf-8"))
        ["plugins"][0]["source"]
        == "./plugins/okto-pulse"
    )
